export const TO_DO_LIST = [
    { id: 101, text: 'Learn React', completed: false },
    { id: 102, text: 'Build a ToDo App', completed: true },
    { id: 103, text: 'Profit!', completed: false },
    { id: 104, text: 'Read about Redux', completed: false },
    { id: 105, text: 'Practice JavaScript ES6+', completed: true },
    { id: 106, text: 'Explore React Hooks', completed: false },
    { id: 107, text: 'Write unit tests', completed: false },
    { id: 108, text: 'Refactor old code', completed: true },
    { id: 109, text: 'Learn TypeScript', completed: false },
    { id: 110, text: 'Try Next.js', completed: false },
    { id: 111, text: 'Add dark mode', completed: true },
    { id: 112, text: 'Improve UI with CSS', completed: false },
    { id: 113, text: 'Learn about REST APIs', completed: true },
    { id: 114, text: 'Connect to a backend', completed: false },
    { id: 115, text: 'Deploy to Vercel', completed: false },
    { id: 116, text: 'Use Git branches', completed: true },
    { id: 117, text: 'Fix bug in ToDo filter', completed: false },
    { id: 118, text: 'Write project README', completed: false },
    { id: 119, text: 'Polish UI animations', completed: true },
    { id: 120, text: 'Learn about testing libraries', completed: false },
];